### ISSUE TITLE
Change package name to @sweetalert/sweetforms

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetforms#4]
Since this project is moved to the org, it'll make sence to rename it accordingly.

**Comment by ChronicStone** [comment]
Sells like NPM won't me use @sweetalert, I don't have authorization to publish on this registry.

I guess you already have a so called NPM registry ? How should we proceed to publish it as @swdetalert/sweetforms

**Comment by limonte** [comment]
Right, I need to add you to npm org in order to publish packages with @sweetalert2 namespace. What's your npm username?

**Comment by ChronicStone** [comment]
It's chronicstone

**Comment by limonte** [comment]
I just send an invitation. After accepting it you should be able to publish with this command

```sh
npm publish --access public
```

**Comment by ChronicStone** [comment]
Done, package is published as @sweetalert2/sweetforms
