### ISSUE TITLE
[ASK FOR FEATURES IDEA] What kind of custom data formats / inputs would you want to be implemented.

### ISSUE THREAD

**Issue by ChronicStone** [sweetalert2/sweetforms#6]
I'm currently developping more data formats types, in order to let users manipulate morre efficiently all kinds of datas, like Arrays and objects. I have a few other ideas but at this point i'll take any idea

For exemple, this a data-table selector, you can pass it array of objects, choose the columns you want to display, map the size of each column as you wantn and select rows which will be the output of the field.

Currently, the table supports Live sorting, Live filtering, Select, Multiple selection at once using shift key. You also have access to a 'cellRenderers' options which allow you to create a custom html template for the columns you want. In this example, the last column is a cellRenderer that displays boolean elegantly. You can use fontawesome icons, in addition to standard html / css for templating cellRenderers

The table is based on grid, so you can map each column with the size you want. Depending on the selectMode optional parameter, you can set the table selection mode to single row (returns an objeect) or multiple rows (returns an array).
Validation also works on it.

Here's an example : 
[LIVE VERSION](https://codesandbox.io/s/solitary-glitter-qxvsq?file=/src/index.js)
```js
// DATA-TABLE FIELD
cellRenderers: {
      booleanRenderer: (value) => {
        if(value) return '<i  style="color:green;" class="fas fa-check"></i>'
        else return '<i style="color:red;" class="fas fa-times"></i>'
      },
      progressRenderer: (value) => {
        return `<progress max="100" value="${value}"></progress>`
      }
 },
fields: [{
        selectMode: 'multiple',
        label: "Select your users", // [REQUIRED] Field label
        key: "table", // [REQUIRED] Key of the field value in the returned object
        type: "data-table", // [REQUIRED] Field type (See availables types above)
        validation: ['required'],
        tableMaxHeight: '40vh',
        gridSize: 16, // Number of units in which the table is divided. You can then choose for each columns the number of units
        columns: [ // Choose only the fields you want to display in table. If your data list has a password, and you dont set password in columns, then password wont be displayed
            {key: "id", label: "ID", colSize: 1  }, 
            {key: "userId", label: "User ID", colSize: 2},
            {key: "title", label: "Email", colSize: 8},
            {key: "progress", label: "Percent done", colSize: 4, cellRenderer: "progressRenderer",},
            {key: "completed", label: "Completed", colSize: 5, cellRenderer: "booleanRenderer"}
        ],
        data: await axios.get('https://jsonplaceholder.typicode.com/todos/').then((response) => response.data.slice(0, 50).map(item => { return { ...item, progress: Math.floor(Math.random() * 100) + 1  }}))
}]
```

![image](https://user-images.githubusercontent.com/55083156/111824568-ae1e2980-88e6-11eb-80fc-0347ec74d72b.png)

This can be extremely useful dealing for example with array of users, you want to select a few of them and get only the ID of the user. You'll then use a customFormatter that will allow you to format array of selected items like this : 
```js
customFormatters: {
    myCustomFormatter: (value) => {
        return value.map(row => row.id)
    }
}
```

If you do have any idea of data format that would be interesting to provide, let me know 😄 

@limonte @Manicraft1001

**Comment by Manicraft1001** [comment]
Sorry for my late response. This looks great. I think is already pretty advanced and doesn't lack any core features. But how about adding / deleting entries? WPF offers DataGrid which has the [CanUserAddRows](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagrid.canuseraddrows?view=net-5.0) property. I don't have the time to check out all features but it looks like the table is currently read-only.
